workflows:
  test-java-extraction:
    name: java ver extraction
    instance_type: mac_mini_m2
    working_directory: ui/espresso/BasicSample
    max_build_duration: 60
    environment:
      vars:
        ANDROID_EMULATOR_NAME: "emulator-34"
    scripts:
      - name: Extract Java version from build.gradle and set JAVA_VERSION and JAVA_HOME
        script: |
          echo "Before extraction: JAVA_VERSION=$JAVA_VERSION, JAVA_HOME=$JAVA_HOME"
          set -e
          BUILD_FILE="build.gradle"
          VERSION_EXTRACTOR="grep -E 'javaVersion\s*=' \"$BUILD_FILE\" | sed -E 's/.*JavaVersion\.VERSION_([0-9]+).*/\1/'"
          javaVersion=$(eval "$VERSION_EXTRACTOR")
          if [[ -z "$javaVersion" ]]; then
            echo "Java version not found in $BUILD_FILE"
            exit 1
          fi
          echo "javaVersion: $javaVersion"
          echo "JAVA_VERSION=$javaVersion" >> $CM_ENV
          # macOS typical Zulu JDK path on Codemagic:
          echo "JAVA_HOME=/Library/Java/JavaVirtualMachines/zulu-$javaVersion.jdk/Contents/Home" >> $CM_ENV
      - name: Build with extracted Java version
        script: |
          echo "Using JAVA_VERSION=$JAVA_VERSION and JAVA_HOME=$JAVA_HOME"
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/app-debug.apk
      - app/build/outputs/androidTest-results/connected/**/*.xml
      - emulator.log

  android-ui-tests-Linux_x2:
    name: Android UI Tests Linux X2
    instance_type: linux_x2
    working_directory: ui/espresso/BasicSample
    max_build_duration: 60
    environment:
      vars:
        ANDROID_EMULATOR_NAME: "emulator-34" # Use one of Codemagic's preinstalled emulators: emulator, emulator-35, emulator-36
    scripts:
      - name: Build Debug APK
        script: ./gradlew assembleDebug
      - name: Launch Android Emulator Headless
        script: |
          $ANDROID_HOME/emulator/emulator -avd $ANDROID_EMULATOR_NAME -no-window -no-audio &
          adb wait-for-device
          adb shell input keyevent 82 # Unlock device screen
      - name: Run UI Instrumented Tests
        script: ./gradlew connectedAndroidTest
      - name: Collect Emulator Logs
        script: adb logcat -d > emulator.log
    artifacts:
      - app/build/outputs/apk/debug/app-debug.apk
      - app/build/outputs/androidTest-results/connected/**/*.xml
      - emulator.log
    
  android-ui-tests-Linux_x4:
    name: Android UI Tests Linux X4
    instance_type: linux_x4
    working_directory: ui/espresso/BasicSample
    max_build_duration: 60
    environment:
      vars:
        ANDROID_EMULATOR_NAME: "emulator-34" # Use one of Codemagic's preinstalled emulators: emulator, emulator-35, emulator-36
    scripts:
      - name: Build Debug APK
        script: ./gradlew assembleDebug
      - name: Launch Android Emulator Headless
        script: |
          $ANDROID_HOME/emulator/emulator -avd $ANDROID_EMULATOR_NAME -no-window -no-audio &
          adb wait-for-device
          adb shell input keyevent 82 # Unlock device screen
      - name: Run UI Instrumented Tests
        script: ./gradlew connectedAndroidTest
      - name: Collect Emulator Logs
        script: adb logcat -d > emulator.log
    artifacts:
      - app/build/outputs/apk/debug/app-debug.apk
      - app/build/outputs/androidTest-results/connected/**/*.xml
      - emulator.log

  android-ui-tests-extended-linux_x2:
    name: Android UI Tests Extended Linux X2
    instance_type: linux_x2
    max_build_duration: 90
    environment:
      vars:
        ANDROID_EMULATOR_NAME: "emulator-34"
    scripts:
      - name: Build BasicSample Debug APK
        working_directory: ui/espresso/BasicSample
        script: ./gradlew assembleDebug

      - name: Run BasicSample UI Tests
        working_directory: ui/espresso/BasicSample
        script: |
          $ANDROID_HOME/emulator/emulator -avd $ANDROID_EMULATOR_NAME -no-window -no-audio &
          adb wait-for-device
          adb shell input keyevent 82
          ./gradlew connectedAndroidTest

      - name: Build IdlingResourceSample Debug APK
        working_directory: ui/espresso/IdlingResourceSample
        script: ./gradlew assembleDebug

      - name: Run IdlingResourceSample UI Tests
        working_directory: ui/espresso/IdlingResourceSample
        script: ./gradlew connectedAndroidTest

      - name: Build RecyclerViewSample Debug APK
        working_directory: ui/espresso/RecyclerViewSample
        script: ./gradlew assembleDebug

      - name: Run RecyclerViewSample UI Tests
        working_directory: ui/espresso/RecyclerViewSample
        script: ./gradlew connectedAndroidTest

      - name: Build IntentsAdvancedSample Debug APK
        working_directory: ui/espresso/IntentsAdvancedSample
        script: ./gradlew assembleDebug

      - name: Run IntentsAdvancedSample UI Tests
        working_directory: ui/espresso/IntentsAdvancedSample
        script: ./gradlew connectedAndroidTest

      - name: Collect Emulator Logs
        script: adb logcat -d > emulator.log

    artifacts:
      - ui/espresso/BasicSample/app/build/outputs/apk/debug/app-debug.apk
      - ui/espresso/BasicSample/app/build/outputs/androidTest-results/connected/**/*.xml
      - ui/espresso/IdlingResourceSample/app/build/outputs/apk/debug/app-debug.apk
      - ui/espresso/IdlingResourceSample/app/build/outputs/androidTest-results/connected/**/*.xml
      - ui/espresso/RecyclerViewSample/app/build/outputs/apk/debug/app-debug.apk
      - ui/espresso/RecyclerViewSample/app/build/outputs/androidTest-results/connected/**/*.xml
      - ui/espresso/IntentsAdvancedSample/app/build/outputs/apk/debug/app-debug.apk
      - ui/espresso/IntentsAdvancedSample/app/build/outputs/androidTest-results/connected/**/*.xml
      - emulator.log

  android-ui-tests-extended-linux_x4:
    name: Android UI Tests Extended Linux X4
    instance_type: linux_x4
    max_build_duration: 90
    environment:
      vars:
        ANDROID_EMULATOR_NAME: "emulator-34"
    scripts:
      - name: Build BasicSample Debug APK
        working_directory: ui/espresso/BasicSample
        script: ./gradlew assembleDebug

      - name: Run BasicSample UI Tests
        working_directory: ui/espresso/BasicSample
        script: |
          $ANDROID_HOME/emulator/emulator -avd $ANDROID_EMULATOR_NAME -no-window -no-audio &
          adb wait-for-device
          adb shell input keyevent 82
          ./gradlew connectedAndroidTest

      - name: Build IdlingResourceSample Debug APK
        working_directory: ui/espresso/IdlingResourceSample
        script: ./gradlew assembleDebug

      - name: Run IdlingResourceSample UI Tests
        working_directory: ui/espresso/IdlingResourceSample
        script: ./gradlew connectedAndroidTest

      - name: Build RecyclerViewSample Debug APK
        working_directory: ui/espresso/RecyclerViewSample
        script: ./gradlew assembleDebug

      - name: Run RecyclerViewSample UI Tests
        working_directory: ui/espresso/RecyclerViewSample
        script: ./gradlew connectedAndroidTest

      - name: Build IntentsAdvancedSample Debug APK
        working_directory: ui/espresso/IntentsAdvancedSample
        script: ./gradlew assembleDebug

      - name: Run IntentsAdvancedSample UI Tests
        working_directory: ui/espresso/IntentsAdvancedSample
        script: ./gradlew connectedAndroidTest

      - name: Collect Emulator Logs
        script: adb logcat -d > emulator.log

    artifacts:
      - ui/espresso/BasicSample/app/build/outputs/apk/debug/app-debug.apk
      - ui/espresso/BasicSample/app/build/outputs/androidTest-results/connected/**/*.xml
      - ui/espresso/IdlingResourceSample/app/build/outputs/apk/debug/app-debug.apk
      - ui/espresso/IdlingResourceSample/app/build/outputs/androidTest-results/connected/**/*.xml
      - ui/espresso/RecyclerViewSample/app/build/outputs/apk/debug/app-debug.apk
      - ui/espresso/RecyclerViewSample/app/build/outputs/androidTest-results/connected/**/*.xml
      - ui/espresso/IntentsAdvancedSample/app/build/outputs/apk/debug/app-debug.apk
      - ui/espresso/IntentsAdvancedSample/app/build/outputs/androidTest-results/connected/**/*.xml
      - emulator.log
    



