workflows:
  android-ui-tests-Linux_x2:
    name: Android UI Tests Linux X2
    instance_type: linux_x2
    max_build_duration: 60
    environment:
      vars:
        ANDROID_EMULATOR_NAME: "emulator-36" # Use one of Codemagic's preinstalled emulators: emulator, emulator-35, emulator-36
    scripts:
      - name: Build Debug APK
        script: ./gradlew assembleDebug
      - name: Launch Android Emulator Headless
        script: |
          $ANDROID_HOME/emulator/emulator -avd $ANDROID_EMULATOR_NAME -no-window -no-audio &
          adb wait-for-device
          adb shell input keyevent 82 # Unlock device screen
      - name: Run UI Instrumented Tests
        script: ./gradlew connectedAndroidTest
      - name: Collect Emulator Logs
        script: adb logcat -d > emulator.log
    artifacts:
      - app/build/outputs/apk/debug/app-debug.apk
      - app/build/outputs/androidTest-results/connected/**/*.xml
      - emulator.log
    test_report:
      - app/build/outputs/androidTest-results/connected/**/*.xml
  
  android-ui-tests-Linux_x4:
    name: Android UI Tests Linux X4
    instance_type: linux_x4
    max_build_duration: 60
    environment:
      vars:
        ANDROID_EMULATOR_NAME: "emulator-36" # Use one of Codemagic's preinstalled emulators: emulator, emulator-35, emulator-36
    scripts:
      - name: Build Debug APK
        script: ./gradlew assembleDebug
      - name: Launch Android Emulator Headless
        script: |
          $ANDROID_HOME/emulator/emulator -avd $ANDROID_EMULATOR_NAME -no-window -no-audio &
          adb wait-for-device
          adb shell input keyevent 82 # Unlock device screen
      - name: Run UI Instrumented Tests
        script: ./gradlew connectedAndroidTest
      - name: Collect Emulator Logs
        script: adb logcat -d > emulator.log
    artifacts:
      - app/build/outputs/apk/debug/app-debug.apk
      - app/build/outputs/androidTest-results/connected/**/*.xml
      - emulator.log
    test_report:
      - app/build/outputs/androidTest-results/connected/**/*.xml
